vich_uploader:
    db_driver: orm

    mappings:
        citation_images:
            uri_prefix: '%citation_images%'
            upload_destination: '%kernel.project_dir%/public/files/citations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
